// export const GENERATION_ACTION_TYPE = 'GENERATION_ACTION_TYPE';

const GENERATION = {
    FETCH: 'GENERATION_FETCH',
    FETCH_ERROR: 'GENERATION_FETCH_ERROR',
    FETCH_SUCCESS: 'GENERATION_FETCH_SUCCESS'
};

const DRAGON = {
    FETCH: 'DRAGON_FETCH',
    FETCH_ERROR: 'DRAGON_FETCH_ERROR',
    FETCH_SUCCESS: 'DRAGON_FETCH_SUCCESS'
}

const ACCOUNT = {
    ADD_SUCCESS: 'ACCOUNT_ADD_SUCCESS',
    FETCH: 'ACCOUNT_FETCH',
    FETCH_ERROR: 'ACCOUNT_FETCH_ERROR',
    FETCH_SUCCESS: 'ACCOUNT_FETCH_SUCCESS',
    FETCH_LOGOUT_SUCCESS: 'ACCOUNT_FETCH_LOGOUT_SUCCESS',
    FETCH_AUTHENTICATED_SUCCESS: 'ACCOUNT_FETCH_AUTHENTICATED_SUCCESS'
};

const ACCOUNT_TRAININGS = {
    FETCH: 'ACCOUNT_TRAININGS_FETCH',
    FETCH_ERROR: 'ACCOUNT_TRAININGS_FETCH_ERROR',
    FETCH_SUCCESS: 'ACCOUNT_TRAININGS_FETCH_SUCCESS'
};

const ACCOUNT_INFO = {
    FETCH: 'ACCOUNT_INFO_FETCH',
    FETCH_ERROR: 'ACCOUNT_INFO_FETCH_ERROR',
    FETCH_SUCCESS: 'ACCOUNT_INFO_FETCH_SUCCESS'
};

const PUBLIC_DRAGONS = {
    FETCH: 'PUBLIC_DRAGON_FETCH',
    FETCH_ERROR: 'PUBLIC_DRAGON_FETCH_ERROR',
    FETCH_SUCCESS: 'PUBLIC_DRAGON_FETCH_SUCCESS'
};

const CONTESTANTS = {
    FETCH: 'CONTESTANTS_FETCH',
    FETCH_ERROR: 'CONTESTANTS_FETCH_ERROR',
    FETCH_SUCCESS: 'CONTESTANTS_FETCH_SUCCESS'
};

const CONTESTANT_INFO = {
    FETCH: 'CONTESTANT_INFO_FETCH',
    FETCH_ERROR: 'CONTESTANT_INFO_FETCH_ERROR',
    FETCH_SUCCESS: 'CONTESTANT_INFO_FETCH_SUCCESS'
};

export {
    GENERATION,
    DRAGON,
    ACCOUNT,
    ACCOUNT_TRAININGS,
    ACCOUNT_INFO,
    PUBLIC_DRAGONS,
    CONTESTANTS,
    CONTESTANT_INFO
};